/**
 * Character Pixel Generator - Main App Entry Point
 * 
 * This is the main application controller that initializes all components
 * and manages the overall character generation workflow.
 */
import { MonsterGenerator } from './generators/monster/monster-generator.js';
import { HumanGenerator } from './generators/human/human-generator.js';
import { MonsterBackstoryGenerator } from './generators/monster/monster-backstory.js';
import { HumanBackstoryGenerator } from './generators/human/human-backstory.js';
import { CharacterRenderer } from './core/renderer.js';

// App modules
import { UIManager } from './app/UIManager.js';
import { ModalManager } from './app/ModalManager.js';
import { ExportManager } from './app/ExportManager.js';
import { SingleModeController } from './app/SingleModeController.js';

class App {
    constructor() {
        // Core properties
        this.canvasSize = 50;
        this.characters = [];
        this.batchOptions = { preset: 'standard' };

        // Initialize generators
        this.monsterGenerator = new MonsterGenerator(this.canvasSize);
        this.humanGenerator = new HumanGenerator(this.canvasSize);
        this.monsterBackstoryGenerator = new MonsterBackstoryGenerator();
        this.humanBackstoryGenerator = new HumanBackstoryGenerator();

        // Initialize renderer
        this.characterRenderer = new CharacterRenderer(3, this.canvasSize);

        // Initialize managers
        this.uiManager = new UIManager(this);
        this.modalManager = new ModalManager(this);
        this.exportManager = new ExportManager(this);

        // State
        this.currentParams = null;
        this.displayOptions = null;

        // Mode state
        this.currentMode = 'batch'; // 'batch' or 'single'
        this.singleModeCharacter = null;
        this.singleModeCharacterIndex = -1; // Index of edited character in the batch
        this.batchCharactersBackup = []; // Backup of batch characters when entering single mode

        // Single Mode Controller
        this.singleModeController = new SingleModeController(this);

        this.init();
        this.setupModalEdit();
    }

    init() {
        this.canvasGrid = document.getElementById('canvasGrid');

        // Initialize display options FIRST (before UI setup triggers regeneration)
        this.displayOptions = {
            showStickFigure: document.getElementById('showStickFigure').checked,
            showThickness: document.getElementById('showThickness').checked,
            showHeatmap: document.getElementById('showHeatmap').checked,
            showFinal: document.getElementById('showFinal').checked,
            showGrid: document.getElementById('showGrid').checked
        };

        // Setup UI (this may trigger regeneration via preset application)
        this.uiManager.setup();
        this.modalManager.setup();

        // Update params from UI (sliders are now initialized)
        this.currentParams = this.uiManager.getParamsFromUI();

        // Generate initial batch if not already generated by setup
        if (this.characters.length === 0) {
            this.generateCharacters(10);
        }
    }

    // --- Getters for current generator based on UI selection ---

    get currentGenerator() {
        const type = document.getElementById('generatorType').value;
        return type === 'human' ? this.humanGenerator : this.monsterGenerator;
    }

    get currentBackstoryGenerator() {
        const type = document.getElementById('generatorType').value;
        return type === 'human' ? this.humanBackstoryGenerator : this.monsterBackstoryGenerator;
    }

    // --- Canvas Size Management ---

    updateCanvasSize(newSize) {
        this.canvasSize = newSize;
        this.monsterGenerator = new MonsterGenerator(this.canvasSize);
        this.humanGenerator = new HumanGenerator(this.canvasSize);
        this.characterRenderer = new CharacterRenderer(3, this.canvasSize);
        this.regenerateCurrentCharacters();
    }

    // --- Loading Overlay ---

    showLoading() {
        const main = document.querySelector('.main-content');
        if (!main) return;
        let overlay = main.querySelector('.loading-overlay');
        if (!overlay) {
            overlay = document.createElement('div');
            overlay.className = 'loading-overlay';
            overlay.innerHTML = '<span class="loading-text">Generating...</span>';
            main.appendChild(overlay);
        }
        overlay.style.display = 'flex';
    }

    hideLoading() {
        const overlay = document.querySelector('.loading-overlay');
        if (overlay) overlay.style.display = 'none';
    }

    // --- Character Generation ---

    generateCharacters(count) {
        if (count >= 10) {
            this.showLoading();
            setTimeout(() => {
                this._doGenerateCharacters(count);
                this.hideLoading();
            }, 20);
        } else {
            this._doGenerateCharacters(count);
        }
    }

    _doGenerateCharacters(count) {
        this.characters = [];
        this.currentBackstoryGenerator.resetPools();

        for (let i = 0; i < count; i++) {
            try {
                const params = this.currentGenerator.randomParamsInRange(this.batchOptions.preset);

                const mergedParams = {
                    ...params,
                    effects: this.currentParams.effects,
                    lightDirection: this.currentParams.lightDirection,
                    outlineColor: this.currentParams.outlineColor
                };

                const character = this.currentGenerator.generate(mergedParams);
                character.backstory = this.currentBackstoryGenerator.generate(character.name);
                this.characters.push(character);
            } catch (err) {
                console.error(`Failed to generate character ${i + 1}/${count}:`, err);
            }
        }

        this.renderCharacters();
    }

    regenerateCurrentCharacters() {
        // In Single Mode, regenerate only the single character
        if (this.currentMode === 'single' && this.singleModeCharacter) {
            this.singleModeController.regeneratePreview();
            return;
        }

        if (this.characters.length === 0) {
            this.generateCharacters(1);
            return;
        }

        const count = this.characters.length;
        if (count >= 10) {
            this.showLoading();
            setTimeout(() => {
                this._doRegenerateCharacters(count);
                this.hideLoading();
            }, 20);
        } else {
            this._doRegenerateCharacters(count);
        }
    }

    _doRegenerateCharacters(count) {
        const oldCharacters = [...this.characters];

        this.characters = [];
        this.currentBackstoryGenerator.resetPools();

        for (let i = 0; i < count; i++) {
            try {
                const oldChar = oldCharacters[i];
                const seed = oldChar.params.seed || Math.floor(Math.random() * 2147483647);

                const params = this.currentGenerator.resolveParams(this.currentParams, seed);

                params.palette = oldChar.params.palette;
                if (oldChar.params.humanColors) {
                    params.humanColors = oldChar.params.humanColors;
                }

                const mergedParams = {
                    ...params,
                    effects: this.currentParams.effects,
                    lightDirection: this.currentParams.lightDirection,
                    outlineColor: this.currentParams.outlineColor
                };

                const character = this.currentGenerator.generate(mergedParams);

                character.name = oldChar.name;
                character.backstory = oldChar.backstory;

                this.characters.push(character);
            } catch (err) {
                console.error(`Failed to regenerate character ${i + 1}/${count}:`, err);
                // Keep the old character on failure
                this.characters.push(oldCharacters[i]);
            }
        }

        this.renderCharacters();
    }

    reprocessCurrentCharacters() {
        // In Single Mode, reprocess only the single character
        if (this.currentMode === 'single' && this.singleModeCharacter) {
            this.singleModeController.regeneratePreview();
            return;
        }

        if (this.characters.length === 0) return;

        this.characters = this.characters.map(char => {
            const newParams = {
                ...char.params,
                effects: this.currentParams.effects,
                lightDirection: this.currentParams.lightDirection,
                outlineColor: this.currentParams.outlineColor
            };

            const reprocessed = this.currentGenerator.reprocess(char, newParams);

            // Invalidate cached animation frames so they're regenerated on-demand
            reprocessed.animationFrames = null;

            reprocessed.name = char.name;
            reprocessed.backstory = char.backstory;
            return reprocessed;
        });

        this.renderCharacters();
    }

    // --- Rendering ---

    redrawCharacters() {
        // Mode-aware redraw: stay in single mode if active
        if (this.currentMode === 'single' && this.singleModeCharacter) {
            this.renderSingleCharacterView(this.singleModeCharacter);
        } else {
            this.renderCharacters();
        }
    }

    renderCharacters() {
        if (!this.canvasGrid) return;

        this.canvasGrid.innerHTML = '';
        this.canvasGrid.className = 'grid-container'; // Reset class for grid view

        this.characters.forEach((character) => {
            const card = document.createElement('div');
            card.className = 'char-card';
            card.style.cursor = 'pointer';
            card.title = 'Click to view details';
            card.addEventListener('click', () => this.modalManager.show(character));

            const canvas = this.characterRenderer.createCanvas();
            this.characterRenderer.drawCharacter(canvas, character, this.displayOptions);
            card.appendChild(canvas);

            // Add name label if in array
            if (character.name) {
                const label = document.createElement('div');
                label.className = 'char-name';
                label.textContent = character.name;
                card.appendChild(label);
            }

            this.canvasGrid.appendChild(card);
        });
    }

    /**
     * Render single character view (large canvas, centered)
     * @param {Object} character - The character to display
     */
    renderSingleCharacterView(character) {
        if (!this.canvasGrid) return;

        this.canvasGrid.innerHTML = '';
        this.canvasGrid.className = 'grid-container single-mode-view';

        const wrapper = document.createElement('div');
        wrapper.className = 'single-char-wrapper';

        // Create larger canvas for single character
        const canvas = document.createElement('canvas');
        const displaySize = Math.min(400, this.canvasSize * 8);
        canvas.width = displaySize;
        canvas.height = displaySize;
        canvas.className = 'single-char-canvas';

        // Draw character scaled up
        const ctx = canvas.getContext('2d');
        ctx.imageSmoothingEnabled = false;

        // Create temp canvas at original size
        const tempCanvas = this.characterRenderer.createCanvas();
        this.characterRenderer.drawCharacter(tempCanvas, character, {
            ...this.displayOptions,
            showFinal: true
        });

        // Draw scaled
        ctx.drawImage(tempCanvas, 0, 0, displaySize, displaySize);

        wrapper.appendChild(canvas);

        // Add character name below
        if (character.name) {
            const nameLabel = document.createElement('h2');
            nameLabel.className = 'single-char-name';
            nameLabel.textContent = character.name;
            wrapper.appendChild(nameLabel);
        }

        // Add backstory preview below name (main area)
        if (character.backstory) {
            const backstoryPreview = document.createElement('p');
            backstoryPreview.className = 'single-char-backstory';
            backstoryPreview.id = 'mainBackstoryPreview';
            backstoryPreview.textContent = character.backstory;
            wrapper.appendChild(backstoryPreview);
        }

        this.canvasGrid.appendChild(wrapper);
    }

    /**
     * Enter single character editing mode
     * @param {Object} character - The character to edit
     */
    enterSingleMode(character) {
        // Backup current batch and remember the character's index
        this.batchCharactersBackup = [...this.characters];
        this.singleModeCharacterIndex = this.characters.indexOf(character);

        // Set mode
        this.currentMode = 'single';
        this.singleModeCharacter = character;

        // Initialize controller
        this.singleModeController.enter(character);

        // Close modal if open
        const modal = document.getElementById('backstoryModal');
        if (modal) modal.style.display = 'none';
        this.modalManager.stopAnimation();

        // Switch UI
        this.uiManager.switchMode('single');
        this.uiManager.populateSingleModeControls(character);

        // Render single character
        this.renderSingleCharacterView(character);
    }

    /**
     * Exit single mode and return to batch view
     */
    exitSingleMode() {
        // Confirm changes
        this.singleModeController.confirm();

        // Restore batch with the edited character written back
        if (this.batchCharactersBackup.length > 0) {
            // Use saved index (primary) or seed-based lookup (fallback)
            let index = this.singleModeCharacterIndex;
            if (index === -1 || index === undefined || index >= this.batchCharactersBackup.length) {
                index = this.batchCharactersBackup.findIndex(
                    c => c.params?.seed === this.singleModeCharacter?.params?.seed
                );
            }
            if (index !== -1) {
                this.batchCharactersBackup[index] = this.singleModeCharacter;
            }
            this.characters = this.batchCharactersBackup;
        }

        // Exit controller
        this.singleModeController.exit();

        // Reset mode
        this.currentMode = 'batch';
        this.singleModeCharacter = null;
        this.singleModeCharacterIndex = -1;
        this.batchCharactersBackup = [];

        // Switch UI
        this.uiManager.switchMode('batch');

        // Restore grid view
        this.canvasGrid.className = 'grid-container';
        this.renderCharacters();
    }

    setupModalEdit() {
        // Setup the "EDIT" button in the modal
        const editBtn = document.getElementById('editCharBtn');
        if (editBtn) {
            editBtn.addEventListener('click', () => {
                const character = this.modalManager.currentCharacter;
                if (!character) return;

                // Use the new enterSingleMode method
                this.enterSingleMode(character);
            });
        }

    }
}

// Initialize app when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    window.app = new App();
});
